version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - npm install -g serverless
  pre_build:
    commands:
      - npm install
  build:
    commands:
      - serverless deploy